### ISSUE TITLE
Implement Dark Mode for iOS 13

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#101]
* https://www.apple.com/newsroom/2019/06/apple-previews-ios-13/

**Comment by bettar** [comment]
Interesting article
https://www.fivestars.blog/code/ios-dark-mode-how-to.html

**Comment by zdavatz** [comment]
Kinda very cool: https://developer.apple.com/design/downloads/SF-Symbols.dmg

**Comment by zdavatz** [comment]
<img width="236" alt="Bildschirmfoto 2019-08-27 um 11 13 04" src="https://user-images.githubusercontent.com/4953/63758451-15ffc000-c8bc-11e9-99e7-db8616e23645.png">

**Comment by zdavatz** [comment]
<img width="236" alt="Bildschirmfoto 2019-08-27 um 11 17 46" src="https://user-images.githubusercontent.com/4953/63758708-81e22880-c8bc-11e9-981f-c498c3919825.png">

**Comment by zdavatz** [comment]
<img width="233" alt="Bildschirmfoto 2019-08-27 um 11 21 14" src="https://user-images.githubusercontent.com/4953/63758897-d08fc280-c8bc-11e9-8a52-e266f0e0d705.png">

**Comment by zdavatz** [comment]
<img width="235" alt="Bildschirmfoto 2019-08-27 um 11 22 00" src="https://user-images.githubusercontent.com/4953/63758939-e4d3bf80-c8bc-11e9-883e-faac1adb622d.png">

**Comment by bettar** [comment]
on a related note, the project is now including "IonIcons", in particular the file ion icons.tff, but it's not clear whether that's actually used or not.

**Comment by zdavatz** [comment]
Can you remove it?

**Comment by bettar** [comment]
what are the names of each icon that you are showing ?

**Comment by zdavatz** [comment]
![68446ACA-94E6-4413-9AF7-F34407ECECBF](https://user-images.githubusercontent.com/4953/63780736-e5824b00-c8e8-11e9-82c6-6d7145ac0907.jpeg)

**Comment by zdavatz** [comment]
the order is the same.

**Comment by zdavatz** [comment]
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/custom-icons/

**Comment by zdavatz** [comment]
https://link.medium.com/EzzwzZPQuZ

**Comment by zdavatz** [comment]
https://www.vtourraine.net/blog/2019/wwdc-2019-sf-symbols

**Comment by zdavatz** [comment]
<img width="129" alt="Bildschirmfoto 2019-08-28 um 09 22 53" src="https://user-images.githubusercontent.com/4953/63834371-7c94e480-c975-11e9-933b-1ef81ab18f28.png">

**Comment by zdavatz** [comment]
iPad symbols need to be replaced as well.

<img width="190" alt="Bildschirmfoto 2019-08-28 um 09 36 48" src="https://user-images.githubusercontent.com/4953/63835267-638d3300-c977-11e9-9735-72aaed80c2e9.png">

**Comment by zdavatz** [comment]
New Scanner Icon:
<img width="135" alt="Bildschirmfoto 2019-08-28 um 10 01 00" src="https://user-images.githubusercontent.com/4953/63836896-c03e1d00-c97a-11e9-9a0c-ed35cb452206.png">

**Comment by zdavatz** [comment]
What are these three dots?

<img width="188" alt="Bildschirmfoto 2019-08-29 um 08 18 43" src="https://user-images.githubusercontent.com/4953/63915195-ad3c5300-ca35-11e9-94ab-e1bb49b20214.png">

**Comment by zdavatz** [comment]
Clear the In-Text searchbar if you start a new search via Präparatename after you done a FTS.

<img width="365" alt="Bildschirmfoto 2019-08-29 um 08 20 01" src="https://user-images.githubusercontent.com/4953/63915245-ce04a880-ca35-11e9-92fe-a40bce1a6f21.png">

**Comment by zdavatz** [comment]
The icons on iPad seem squeezed.

<img width="176" alt="Bildschirmfoto 2019-08-29 um 08 33 50" src="https://user-images.githubusercontent.com/4953/63916011-bdedc880-ca37-11e9-8d51-dcfd8712af6d.png">

**Comment by zdavatz** [comment]
iPad Screen does not reach the bottom.

<img width="304" alt="Bildschirmfoto 2019-08-29 um 08 37 59" src="https://user-images.githubusercontent.com/4953/63916244-5126fe00-ca38-11e9-8e18-a7c33801e7c2.png">

**Comment by zdavatz** [comment]
Interactions are still white

<img width="1051" alt="Bildschirmfoto 2019-08-29 um 08 40 59" src="https://user-images.githubusercontent.com/4953/63916458-c4307480-ca38-11e9-8829-d6019195372f.png">

**Comment by zdavatz** [comment]
Prescription history has with edges at bottom and top.
<img width="224" alt="Bildschirmfoto 2019-08-29 um 08 45 17" src="https://user-images.githubusercontent.com/4953/63916749-56d11380-ca39-11e9-8e02-9fe5b164f7a3.png">

**Comment by zdavatz** [comment]
home icon.
<img width="131" alt="Bildschirmfoto 2019-08-29 um 09 16 33" src="https://user-images.githubusercontent.com/4953/63918811-b5988c00-ca3d-11e9-8bcb-53ab19916098.png">

**Comment by bettar** [comment]
> What are these three dots?
> 
> <img alt="Bildschirmfoto 2019-08-29 um 08 18 43" width="188" src="https://user-images.githubusercontent.com/4953/63915195-ad3c5300-ca35-11e9-94ab-e1bb49b20214.png">

I think they are a placeholder for a "right" item on the navigation bar. Maybe they have always been there, but for some devices they are hidden under the search bar. For example iPhone 8 shows the search bar extending all the way to the right and covering them, for iPhone XR the search bar is narrower and the three dots are visible.

**Comment by zdavatz** [comment]
<img width="370" alt="Bildschirmfoto 2019-08-29 um 13 48 17" src="https://user-images.githubusercontent.com/4953/63937834-a9272a00-ca63-11e9-93ed-4d40e9b3100c.png">

**Comment by zdavatz** [comment]
sidebar ist still white.

**Comment by zdavatz** [comment]
At iPad Startup I get this:

<img width="597" alt="Bildschirmfoto 2019-08-29 um 13 52 25" src="https://user-images.githubusercontent.com/4953/63938065-3ec2b980-ca64-11e9-91a2-d3ec76f46c9c.png">

**Comment by zdavatz** [comment]
<img width="238" alt="Bildschirmfoto 2019-08-30 um 08 41 23" src="https://user-images.githubusercontent.com/4953/63998685-f5c14280-cb01-11e9-8a79-f61df2422cf3.png">

**Comment by zdavatz** [comment]
1. Camera is not a square yet https://github.com/zdavatz/AmiKo-iOS/issues/101#issuecomment-525630487
2. Prescription history has white top and bottom https://github.com/zdavatz/AmiKo-iOS/issues/101#issuecomment-526048693
3. Make searchbar wider https://github.com/zdavatz/AmiKo-iOS/issues/101#issuecomment-526041626
4. In-Text Search is not cleared and the index of the In-Text Search is wrong if nothing is found: https://github.com/zdavatz/AmiKo-iOS/issues/101#issuecomment-526041994
