### ISSUE TITLE
Positioning of In-Text-Counter is not correct

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#103]
`1/2` should be aligned more to the right.
<img width="372" alt="Bildschirmfoto 2019-09-02 um 17 32 42" src="https://user-images.githubusercontent.com/4953/64124718-01359780-cda8-11e9-98ca-c21476c51d30.png">

<img width="816" alt="Bildschirmfoto 2019-09-02 um 17 37 50" src="https://user-images.githubusercontent.com/4953/64124837-68ebe280-cda8-11e9-9a80-254c0f7e51b8.png">

Here no counter should be shown.
<img width="369" alt="Bildschirmfoto 2019-09-02 um 17 31 45" src="https://user-images.githubusercontent.com/4953/64124696-f5e26c00-cda7-11e9-9754-8d1053b16f36.png">

**Comment by bettar** [comment]
I guess the bad positioning only applies to iPhone 8 Plus and iPhone XR, and only in Portrait orientation. Confirmed ?

**Comment by zdavatz** [comment]
Happens on Xs Max too. See above.
