### ISSUE TITLE
In-Text-Search jumps away when doing FTS

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#105]
1. Open AmiKo App
2. Navigate to FTS
3. Search for "SAPPHIRE"
3. Tap on "SAPPHIRE" in FTS.
4. Results jumps away.

See: https://ywesee.slack.com/files/U27FC8WLA/FNJSW8S6Q/file_from_ios.mp4

**Comment by bettar** [comment]
There is one more step between 4 and 5

**Comment by bettar** [comment]
The video shows two examples, and they both have only one result. So in the video it is correct that the Previous/Next navigation gets hidden.

**Comment by bettar** [comment]
It's worth pointing out that it works on the simulator

**Comment by zdavatz** [comment]
works.
