### ISSUE TITLE
Downloading latest App still asks for DB update

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#106]
1. Download the latest App.
2. Open the.
3. App still says the DB is older then 30 day.

**Comment by bettar** [comment]
"Download" is ambiguous:

- case1: first time it gets installed
- case2: app gets updated

I think you are referring to case2. In this case how can the app know that it's just being updated ?

**Comment by zdavatz** [comment]
Just use the new DB of the updated App.

**Comment by zdavatz** [comment]
With Android we check for the Timestamp: https://github.com/zdavatz/AmiKo-Android/pull/148/commits/e141b02ab2526cfe623adb8b2c572c91a74a723e

**Comment by bettar** [comment]
I think now it uses the bundled DB only in case 1

**Comment by zdavatz** [comment]
Ok, that we need to improve. It should always use he bundled DB or at least check if the DB of the Updated App is newer, if so, use it.

**Comment by bettar** [comment]
At which point is that check done in Android?
- every time the app launches ?
- every time the app updates the DB ?
- every time the app is updated ?

**Comment by zdavatz** [comment]
You can also see this: https://github.com/zdavatz/AmiKo-Android/pull/148/commits/64b143ebea749ccc23d6d4a7b8d5cda749e354cd

**Comment by zdavatz** [comment]
Check when the App is being updated.

**Comment by bettar** [comment]
And how would the App know that is has been updated ?

**Comment by zdavatz** [comment]
i.e. through the version number of the App.

**Comment by bettar** [comment]
and it compares that version number with what?

**Comment by zdavatz** [comment]
i.e. previous version.

**Comment by bettar** [comment]
previous version being stored where ?

**Comment by zdavatz** [comment]
Do you not have a build timestamp?

**Comment by bettar** [comment]
of the previous version?

**Comment by zdavatz** [comment]
yes.

**Comment by bettar** [comment]
It sounds like you are mixing the build version of the app with the DB version, old and new, in total 4 version numbers.

**Comment by zdavatz** [comment]
you can store a app version number in NSUserDefaults and check it every time your app is launched. If the number is not available, its a fresh installation. If it is changed , it is an upgrade.

https://stackoverflow.com/questions/16899503/check-if-my-ios-application-is-updated
