### ISSUE TITLE
Cancel Update ignored

### ISSUE THREAD

**Issue by bettar** [zdavatz/AmiKo-iOS#108]
Steps to reproduce:
Pill menu, Update, then after a few seconds of download tap "Cancel"

Problem:
the update still seems to go through and the Cancel is ignored, at least that's what the pop up message says at the end.

Interesting to note that the Android version of the App doesn't have the Cancel button.

**Comment by zdavatz** [comment]
How about we just remove the cancel button?

**Comment by zdavatz** [comment]
Or we could fix the Cancel Button.

**Comment by bettar** [comment]
So which way is it , remove or fix ?
If you want to fix it, what is the intended behaviour ? should the Cancel abort only the current download or all pending downloads ?

**Comment by zdavatz** [comment]
what is the difference between "pending" and "current"?

**Comment by bettar** [comment]
For each update there are 4 files to be downloaded. For example one has been completely downloaded, the second one is half way through when we tap Cancel. This this the "current" one. The remaining two in the queue are the "pending" ones

**Comment by zdavatz** [comment]
"Cancel" removes all files also the ones that have already been downloaded.

**Comment by zdavatz** [comment]
Show one progress bar for download (for all files) after that show one progress bar for unzipping (for all files).

During the progress of downloading/unzipping show the file name and size downloaded/unziped.

This should happen sequentially.
