### ISSUE TITLE
Enable iCloud Sync

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#112]
Ermöglichen von iCloud-Sync, sodass die Arztadresse und Selfie, Patienten-Datenbank und alle Rezepte in der iCloud gespeichert werden können. Wenn man sein App löscht und neu installiert, dann muss man die Daten wieder abrufen können von iCloud.

Der User muss iCloud aktivieren oder deaktivieren können.

**Comment by b123400** [comment]
Meine Todo-Liste.
Migration:
- [x] Amk Dateien kopieren
- [x] Arzt Dateien kopieren 
- [ ] Patienten vom Sqlite zu CloudKit kopieren
----
- [x] Arzt Datei lesen
- [x] Arzt Datei schreiben 
- [x] Arzt "signature.png" Datei lesen 
- [x] Arzt "signature.png" Datei schreiben
- [ ] Amk Dateien lesen
- [ ] Amk Dateien schreiben
- [ ] Patienten lesen
- [ ] Patienten schreiben
----
- [ ] Setting View

**Comment by zdavatz** [comment]
Super, Danke!

**Comment by zdavatz** [comment]
etwas klappt noch nicht mit der Patienten-Datenbank.

1. Ich installiere die App.
2. Füge den Arzt hinzu.
3. Füge einen Patienten hinzu.
4. Aktivere iCloud Sync.
5. Lösche die App.
6. Installiere die App wieder.
7. Aktiviere iCloud Sync.
8. Die Arztadresse erscheint wieder.
9. Die Patientenadresse ist aber nicht mehr da. -> muss ich ein Rezept erstellen, damit die Patienten-Adresse gespeichert wird?

**Comment by b123400** [comment]
Ich habe das versuchen, aber es klappt für mich. Vielleicht es braucht einige Zeit.

**Comment by zdavatz** [comment]
Ok, versuche es nochmals.

**Comment by zdavatz** [comment]
Arztadresse und Favoriten werden jetzt in iCloud gespeichert.
1. Ich installiere die App.
2. Aktivere iCloud Sync.
3. Füge den Arzt hinzu.
4. Füge einen Patienten hinzu und erstelle ein Rezept.
5. Lösche die App.
6. Installiere die App wieder.
7. Aktiviere iCloud Sync.
8. Die Arztadresse erscheint wieder.
9. Die Favoriten erscheinen wieder.
**10. Die Patientenadresse ist aber nicht mehr da und das Rezept auch nicht.**

**Comment by b123400** [comment]
Entschldigung, Ich habe CloudKit Deployment zu Produktion vergessen. Es sollt jetzt klappen.

**Comment by zdavatz** [comment]
Danke, werde es versuchen!

**Comment by zdavatz** [comment]
> Entschldigung, Ich habe CloudKit Deployment zu Produktion vergessen. Es sollt jetzt klappen.

Wie hast Du die Deployment gemacht? Kannst Du bitte ein Screenshot teilen?

**Comment by b123400** [comment]
Ich habe die Deployment gemacht auf CloudKit Dashboard:
https://icloud.developer.apple.com/dashboard/#containers/iCloud.com.ywesee.AmikoDesitin

<img width="1165" alt="CloudKit Dashboard 2020-04-05 00-42-42" src="https://user-images.githubusercontent.com/127193/78455015-d3feee00-76d6-11ea-93be-635d6facabe7.png">

**Comment by zdavatz** [comment]
> Ich habe die Deployment gemacht auf CloudKit Dashboard:
> https://icloud.developer.apple.com/dashboard/#containers/iCloud.com.ywesee.AmikoDesitin
> 
> <img alt="CloudKit Dashboard 2020-04-05 00-42-42" width="1165" src="https://user-images.githubusercontent.com/127193/78455015-d3feee00-76d6-11ea-93be-635d6facabe7.png">

Super, Danke, dann werde ich nachher nochmals testen.

**Comment by zdavatz** [comment]
Es klappt wunderbar, sehr schön!
