### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#116]
Wie können wir das in Zukunft umgehen?
```
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
```

**Comment by zdavatz** [comment]
![Bildschirmfoto 2020-04-02 um 20 08 00](https://user-images.githubusercontent.com/4953/78283183-bcc8d080-751d-11ea-973a-c977a9ca8c09.png)

**Comment by b123400** [comment]
Um... Ich kann nicht UIWebView gefinden in das Projekt... Haben Sie `pod install` vor erstellen laufen?

**Comment by zdavatz** [comment]
Ich werde schauen, Danke!

**Comment by zdavatz** [comment]
Ich denke, es braucht kein Pod-Install, siehe:

```
zdavatz@Zenos-iMac:~/Documents/xcode/amiko-ios$ pod install
Analyzing dependencies
Downloading dependencies
Removing WebViewJavascriptBridge
Generating Pods project
=== Target: Pods-AmiKoDesitin
=== Target: Pods-CoMedDesitin
Integrating client project
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

[!] The Podfile does not contain any dependencies.
```

**Comment by b123400** [comment]
Die vorherig Version benutzt `WebViewJavascriptBridge`, welche benutzt `UIWebView.` Wir wollen UIWebView nicht, also Ich habe `WebViewJavascriptBridge` gelöscht. Wenn Sie `pod install` laufen, `WebViewJavascriptBridge` ist vom die Projekt gelöscht.

Wir brauchen in der Tat Cocoapod nicht mehr.

**Comment by zdavatz** [comment]
> Die vorherig Version benutzt `WebViewJavascriptBridge`, welche benutzt `UIWebView.` Wir wollen UIWebView nicht, also Ich habe `WebViewJavascriptBridge` gelöscht. Wenn Sie `pod install` laufen, `WebViewJavascriptBridge` ist vom die Projekt gelöscht.
> 
> Wir brauchen in der Tat Cocoapod nicht mehr.

dann bitte Cocoapod entfernen aus dem Code.

**Comment by zdavatz** [comment]
ich habe das gemacht:
```
zdavatz@Zenos-iMac:~/Documents/xcode/amiko-ios$ pod install
Analyzing dependencies
Downloading dependencies
Removing WebViewJavascriptBridge
Generating Pods project
=== Target: Pods-AmiKoDesitin
=== Target: Pods-CoMedDesitin
Integrating client project
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

[!] The Podfile does not contain any dependencies.
```

**Comment by b123400** [comment]
Aber Ich denke, wir brauchen vielleicht es wieder in Zukunft? Es gibt kein Nachteil.

**Comment by zdavatz** [comment]
ok, wie du meinst, dann lassen wir es.
