### ISSUE TITLE
_Save as new_ is only option when swapping patient

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#21]
1. Open patient
2. Select prescription from AMK list
3. Click patient
4. Select new patient
5. Now the User should only have one option: _Save as new_. There is no use for an option _Overwrite prescription_, because this is a new prescription for that patient.
6. Overwrite prescription basically only happens for editing an existing prescription for the same patient. If you swap the patient there is only one option: Save as new.

**Comment by bettar** [comment]
It's a bit tricky, because if after selecting a new patient the user selects the original patient, the Overwrite options should be there.
