### ISSUE TITLE
Make doctor view swipeable.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#3]
Whenever there is am "Hamburger" the view should be swipeable.

**Comment by bettar** [comment]
This is not straightforward to debug and fix, because it seems to work in the simulator.

**Comment by zdavatz** [comment]
The doctor view is not swipeable in the simulator.

**Comment by bettar** [comment]
It is in my simulator

**Comment by zdavatz** [comment]
How do you swipe?

**Comment by zdavatz** [comment]
Where do you place the mouse in the doctor view when you pull to the right?

**Comment by bettar** [comment]
I start dragging from near the left edge. It doesn't seem to be critical the exact spot.

**Comment by zdavatz** [comment]
Where? Below the fields (below the Selfie) or at which field name?

**Comment by bettar** [comment]
For example, I start dragging with the mouse exactly from the "Z" of the ZIO label.

**Comment by zdavatz** [comment]
Ok, that does not happen in my simulator. Can you test with an iPhone attached to the iMac?

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/3648967/how-to-recognize-swipe-gesture-in-uiscrollview/3652999

**Comment by bettar** [comment]
Disabling the scroll action as suggested in the link you posted seems to have fixed it !

**Comment by bettar** [comment]
The problem is with the patient view now. If we make it non scrollable there is no way of getting to the fields at the bottom. I wonder why with the simulator you can have both things.

**Comment by bettar** [comment]
I think I found the proper way of fixing this: rather that disabling the "scroll" action we need to disable the "bounce" action.

**Comment by zdavatz** [comment]
Yes, agreed.

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/500761/stop-uiwebview-from-bouncing-vertically

**Comment by zdavatz** [comment]
This has been fixed with commit ac77890e0e341d370
