### ISSUE TITLE
Make link if doctor address is missing look nicer.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#30]
If the doctor address is missing please create a link:
"Please add doctor's address." (EN)
"Bitte Arztadresse hinzufügen." (DE)
"Rajoutez l’adresse du médecin svp." (FR)

If you tap the link, it opens the address view to edit the doctor's address.
https://files.slack.com/files-tmb/T27F6280H-F9VUKPWL8-e48d9423d1/_1024.png

**Comment by bettar** [comment]
Why just asking to add the doctor's address ? The message should prompt to enter the complete doctor's profile, not just the address field.

**Comment by zdavatz** [comment]
The link takes the User to the address entry page of the doctor.

**Comment by zdavatz** [comment]
by "address" I mean all mandatory fields of the doctor page.

**Comment by zdavatz** [comment]
1. Make Text smaller (same size like "Doctor")
2. Make link "yellow" like other links
3. Remove space at beginning

**Comment by bettar** [comment]
You had an error on the Travis CI build, that's why you didn't see the changes.

**Comment by zdavatz** [comment]
Thank you, I can seen them now. Almost perfect.
