### ISSUE TITLE
Importing second prescription from different doctor shows wrong doctor address

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#32]
I just sent two Emails with attachments to test importing the attachments out of the real Mail App on your iPhone to a...@i..com. Something is still really wrong there. Please test the import of all prescriptions on your real device. Steps to reproduce:
1. Set doctor address on real device, with selfie. Click save.
2. Now start importing prescriptions from Mail app from the Mails I just sent (Test _Emese_ and Test _Yuka_)
3. The user is not taken to the correct prescription when importing the prescriptions

**Comment by bettar** [comment]
Decoding Emese's RZ_2018-02-28T182110.amk from the command line I get Invalid character in input stream.

**Comment by zdavatz** [comment]
works perfectly fine on my Mac and on my Linux machine with
```
cat RZ_2018-02-28T182110.amk | base64 --decode
```

**Comment by zdavatz** [comment]
how did you download the file?

**Comment by bettar** [comment]
From email attachment, like the other two.

**Comment by bettar** [comment]
The title talks about different doctors, but all the AMK in the email attachment are form the same doctor. Please explain.

**Comment by zdavatz** [comment]
Just import another prescription from another doctor.

**Comment by zdavatz** [comment]
Seems to work with Commit 6ef0aef6d08c98c572e9f982eed1c3085b9d9e8a
