### ISSUE TITLE
Make menu point to correct entry, when using iPad

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#34]
This is "wrong"
<img width="733" alt="bildschirmfoto 2018-03-29 um 15 30 10" src="https://user-images.githubusercontent.com/4953/38091541-20f0611e-3366-11e8-920c-ac81e79bf2a6.png">

<img width="575" alt="bildschirmfoto 2018-03-29 um 15 31 49" src="https://user-images.githubusercontent.com/4953/38091639-676d280c-3366-11e8-91e7-ca2832f07a4b.png">

This is correct or better.

https://files.slack.com/files-tmb/T27F6280H-F9Y69QSG2-a57bf32885/image_uploaded_from_ios_1024.png

Make menu point to correct entry when using iPad to select package.

**Comment by bettar** [comment]
The Cancel button is ALWAYS missing for iPad. This seems to be the general guidelines from Apple: canceling is done by tapping outside. If you really want it we can put it there.

**Comment by zdavatz** [comment]
This works now for the prescription view but not yet for package view (first screen shot).

**Comment by zdavatz** [comment]
Works for package view too now!
