### ISSUE TITLE
My Tab Bar.Bottom does not reload icons correctly after rotation

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#38]
My Tab Bar Bottom does not reload correctly after rotation. Have a look at the items at the end of the movie.

https://ywesee.slack.com/files/U27FC8WLA/FA0G4PAR4/icons_need_to_be_reloaded_as_well.mov

This seems to be a similar issue like #37

**Comment by zdavatz** [comment]
These two lines both show the Tabbar in Landscape mode after rotating.

https://github.com/zdavatz/AmiKo-iOS/blob/master/AmikoDesitin/MLViewController.m#L901

https://github.com/zdavatz/AmiKo-iOS/blob/master/AmikoDesitin/MLViewController.m#L1044

**Comment by zdavatz** [comment]
<img width="606" alt="bildschirmfoto 2018-04-12 um 14 14 33" src="https://user-images.githubusercontent.com/4953/38676647-ffd1be6e-3e5b-11e8-88b9-5e225591265e.png">

**Comment by bettar** [comment]
https://github.com/zdavatz/AmiKo-iOS/blob/40ad78d64dee849f43758151954e3ec008c0972c/AmikoDesitin/MLSecondViewController.m#L318

**Comment by zdavatz** [comment]
Closing this with commit 487cde765d6ac1df25ca8cc45e0b2c018698e2ca
