### ISSUE TITLE
Why is this not French?

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#51]
<img width="523" alt="bildschirmfoto 2018-04-06 um 20 08 50" src="https://user-images.githubusercontent.com/4953/38437124-c9575544-39d6-11e8-86f7-f2e05d31c3c1.png">

This needs to be checkt for the other languages as well.

**Comment by zdavatz** [comment]
<img width="500" alt="bildschirmfoto 2018-04-06 um 20 13 40" src="https://user-images.githubusercontent.com/4953/38437244-27ff1d7a-39d7-11e8-88b1-d9c77dfba295.png">

**Comment by bettar** [comment]
I cannot reproduce the problem. In my tests it's in French.

**Comment by zdavatz** [comment]
Did you compile CoMed? Did you run it with CoMed?

**Comment by bettar** [comment]
No, there was nothing in this page mentioning CoMed until now.

**Comment by zdavatz** [comment]
Always test on CoMed as well, as mentioned in the conversation we had..
