### ISSUE TITLE
Linking the Hamburgers always with the same swipe-gesture.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#52]
Hamburges need to be linked always with the same view. We discussed this once.

**Comment by bettar** [comment]
And what was the outcome of the discussion ?

**Comment by zdavatz** [comment]
You said it should be possilbe.

**Comment by zdavatz** [comment]
Discussion. Detecting the swipe Back (right to left) from AmiKo-address-book-view to Patient-Edit-View should link the swipe action back to iOS-address-book-view (right to left).

**Comment by zdavatz** [comment]
Closing this for the time being.
