### ISSUE TITLE
Searchbar is still being misplaced after rotation

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#58]
<img width="341" alt="bildschirmfoto 2018-04-12 um 17 07 22" src="https://user-images.githubusercontent.com/4953/38686207-1e78665c-3e74-11e8-9fac-61cb30b015e9.png">

**Comment by bettar** [comment]
Sorry, I cannot reproduce it. What are the steps to see the problem ? Which device, any device ?

**Comment by zdavatz** [comment]
Focus on #57. I am trying to reproduce the issue. So far no luck.

**Comment by zdavatz** [comment]
I am using the latest commit.

**Comment by zdavatz** [comment]
Steps to reproduce:
1. Open Application.
2. Search for Ponstan
3. Rotate Device
4. Tap the Fachinfo in LS mode to show the Fachinfo-Text.
5. Click Hamburger in top left corner in LS mode.
6. Rotate back. 
7. Search bar is misplaced.

This is reproducable in the simulator.
