### ISSUE TITLE
Print Prescription

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#63]
1. Create a prescription
2. Add a patient
3. Add a package or several packages.
4. Add some comments.
5. Click _Send_
6. User should get an option to print the Table view either to a printer (via AirPrint) or a PDF
7. Same Format like macOS.

**Comment by zdavatz** [comment]
https://ywesee.slack.com/files/U27FC8WLA/FC6TG1FA5/file.jpg

Print Preview is empty.

**Comment by zdavatz** [comment]
still some overlapping by the comment.
![](https://ywesee.slack.com/files/U27FC8WLA/FCDPLRLRL/file.jpg)

**Comment by zdavatz** [comment]
left align 
https://ywesee.slack.com/files/U27FC8WLA/FCC758R0U/file.jpg

**Comment by zdavatz** [comment]
1. Add document name.
2. Add page number if more then ine page.
3. Add the amk File-name.

**Comment by zdavatz** [comment]
1. Remove the rectangle.
2. Add filename.
3. Add Pagination.
then we are done with this task.

**Comment by bettar** [comment]
What's the German and French localization for "Page 1" ?

**Comment by zdavatz** [comment]
German: "Seite 1"
French: "Page 1"

**Comment by bettar** [comment]
Also, in your comment above from 6 days ago, what's the difference between:
1. Add document name.
and
3. Add the amk File-name.
?

**Comment by zdavatz** [comment]
I would say it is the same.
