### ISSUE TITLE
Scan EAN13 Barcodes using Camera, go Full-Screen on all devices.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#74]
Scan [EAN13](https://developer.apple.com/documentation/vision/vnbarcodesymbologyean13?language=objc) to add a package to the prescription. Use these [barcodes](https://amiko.oddb.org/de/fi?gtin=7680392710614&type=title&key=pons) to test.

**Comment by zdavatz** [comment]
Longtap onto the header of the _Medicines (0)_ table.

**Comment by zdavatz** [comment]
- When the barcode is detected in the video stream use it, close the camera view and add the package to the prescription.
- There is no need to have an overlay. 
- There is no need to handle the rotation.

**Comment by bettar** [comment]
Do you need a Cancel button like for the health card OCR preview ?

**Comment by zdavatz** [comment]
We still need to go full-screen for all the devices.

**Comment by zdavatz** [comment]
App Crashes in Simulator when Long-Tapping on Medicines Table Header.
1. Start App in iPhoneX simulator
2. Goto Prescriptions
3. Longtap Medicines Table Header
4. App Crashes.

**Comment by zdavatz** [comment]
App Crashes on iPad when doing the followin:
1. Start App
2. Goto Prescriptions
3. Longtap on Medicines Table header
4. Wait for Scanner
5. Hit Cancel
6. Now the App hangs and my crash, see: https://gist.github.com/zdavatz/d09e05d1d52c4bce098ae390624818bd
