### ISSUE TITLE
Print Label.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#76]
Add a Long-Tap option to print the label. See: 
https://files.slack.com/files-pri/T27F6280H-FBRGBRM8W/file.jpg

**Comment by zdavatz** [comment]
EN: Print Label.
DE: Etikette drucken.
FR: Imprimer l'étiquette.

**Comment by bettar** [comment]
Long-tap to what ?

**Comment by zdavatz** [comment]
Yes. Same menu where you add the comment for the package.

**Comment by bettar** [comment]
The label printer "DYMO LabelWriter 450" doesn't seem to be available for AirPrint. See also https://support.apple.com/en-us/HT201311

**Comment by bettar** [comment]
Also, assuming that it is possible to share the DYMO printer with AirPrint, do you want an intermediate printer picker step to select the printer (at least the first time) or do you want to print directly ?

**Comment by zdavatz** [comment]
I guess if you connect the Dymo 450 to the [Aiport Express](https://www.apple.com/shop/product/MC414LL/A/airport-express) then you can print using AirPrint.

**Comment by zdavatz** [comment]
The first time the saved printer is not decided. Printer selection is shown. The second time it will just use the previous selection, unless the selected printer is not found. If it is not found then ask again.

**Comment by zdavatz** [comment]
Printing [Paper Size](https://stackoverflow.com/questions/28321679/custom-print-size-in-ios) in iOS.

**Comment by bettar** [comment]
The link above is not very useful. That delegate method doesn't even get called, and if it did it would specify only the length of the label, not the width.

**Comment by zdavatz** [comment]
Look at the [Apple Airprint API](https://developer.apple.com/airprint/) and [printPaper](https://developer.apple.com/documentation/uikit/uiprintinteractioncontroller/1618165-printpaper?language=objc)

**Comment by zdavatz** [comment]
Why don't we do [printableRect](https://developer.apple.com/documentation/uikit/uiprintpaper/1623530-printablerect?language=objc)?

**Comment by zdavatz** [comment]
[drawHeaderForPageAtIndex:inRect:](https://developer.apple.com/documentation/uikit/uiprintpagerenderer/1621639-drawheaderforpageatindex?language=objc)

**Comment by zdavatz** [comment]
[printing a custom view](https://developer.apple.com/documentation/uikit/uiviewprintformatter?language=objc)

**Comment by zdavatz** [comment]
[UIPrintFormatter](https://developer.apple.com/documentation/uikit/uiprintformatter?language=objc)

**Comment by zdavatz** [comment]
Check this [PrintPDF](https://stackoverflow.com/questions/48702659/uiprintpagerenderer-paper-size-not-changing)

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/32403634/airprint-contents-of-a-uiview

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/21802435/change-printed-size-of-image-in-ios

**Comment by zdavatz** [comment]
https://nshipster.com/uiprintinteractioncontroller/

**Comment by zdavatz** [comment]
Download the printer simulator: 
https://download.developer.apple.com/Developer_Tools/Additional_Tools_for_Xcode_9.3/Additional_Tools_for_Xcode_9.3.dmg

**Comment by zdavatz** [comment]
If the printer _has never been selected_, then _show_ the preview.
If the printer _has been_ selected then _do not_ show the preview.

**Comment by zdavatz** [comment]
Even if the label is very wide, it does not fit.

[label-1-output_long_iphone.pdf](https://github.com/zdavatz/AmiKo-iOS/files/2278688/label-1-output_long_iphone.pdf)

**Comment by zdavatz** [comment]
This is the label size I choose.
<img width="333" alt="bildschirmfoto 2018-08-10 um 19 36 01" src="https://user-images.githubusercontent.com/4953/43970005-ad3b5534-9cd4-11e8-8c6b-48214398a95e.png">

**Comment by zdavatz** [comment]
Direkt Comparison:

<img width="556" alt="bildschirmfoto 2018-08-10 um 19 41 15" src="https://user-images.githubusercontent.com/4953/43970172-5f2e28f2-9cd5-11e8-8761-6ef6252eea0e.png">

**Comment by zdavatz** [comment]
almost there https://ywesee.slack.com/files/U27FC8WLA/FC89R20FQ/file.jpg

**Comment by zdavatz** [comment]
It's cutoff by the "Seite 1" rectangle. If there is a way of disabling the page number, you'll see that it's not cutoff.
