### ISSUE TITLE
Crash when saving a new prescription after adding packages with Scanner.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#77]
1. Open App
2. Select patient.
3. Scan three Barcodes from packages.
4. Long-Tap one package.
5. Add a comment to the package.
6. Click "Save as new prescription"
7. App Crashes.

**Comment by zdavatz** [comment]
Das Log
```
https://gist.github.com/zdavatz/a293b98d917e0804e991f468ae6a46be
```

**Comment by bettar** [comment]
Das Log "AmiKo Desitin.exe" on iOS ?

**Comment by zdavatz** [comment]
Sorry, work paste to many VMs open! :/ :)

**Comment by zdavatz** [comment]
But iOS Bug still happens

**Comment by zdavatz** [comment]
commit 9885dfe57f97ef9d9049da6ad11 works.
