### ISSUE TITLE
Longtapping on Medicines bar on iPhoneX simulator takes a lot longer to load video View

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#79]
Longtapping on _Medicines bar_ in iPhoneX simulator takes a lot longer to load video View **then** longtapping on Camera to load the camera view to scan insurance card. Longtapping to load camera via for card scanning is very fast. So is cancelling the camera view of the insurance card scanner.

**Comment by bettar** [comment]
Is that also happening on the real device iPhone X or only with the simulator ?
