### ISSUE TITLE
No Cancel button in Landscape mode.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#81]
<img width="346" alt="bildschirmfoto 2018-07-27 um 15 09 57" src="https://user-images.githubusercontent.com/4953/43320085-edb5dccc-91af-11e8-8437-f4d1325cd90b.png">
<img width="324" alt="bildschirmfoto 2018-07-27 um 15 10 12" src="https://user-images.githubusercontent.com/4953/43320086-eddfb470-91af-11e8-8c38-79e9c9e016a6.png">

**Comment by zdavatz** [comment]
<img width="344" alt="bildschirmfoto 2018-07-27 um 15 22 57" src="https://user-images.githubusercontent.com/4953/43320403-04d8a834-91b1-11e8-8846-59f2690ae31b.png">
<img width="340" alt="bildschirmfoto 2018-07-27 um 15 23 14" src="https://user-images.githubusercontent.com/4953/43320404-04fc3bdc-91b1-11e8-931b-efc0ed675785.png">

**Comment by bettar** [comment]
What are you pointing out with those screen captures ?

**Comment by zdavatz** [comment]
works great, thank you!
