### ISSUE TITLE
Town of doctor and date are missing in iOS label print setup

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#83]
see Label print preview of macOS. See:
[macOS_prescription.pdf](https://github.com/zdavatz/AmiKo-iOS/files/2263321/macOS_prescription.pdf)

**Comment by bettar** [comment]
We know that the label preview is not correct, because we are not using the correct paper size. When the label is actually printed on paper, the doctor town and date are on the label.
