### ISSUE TITLE
Insurance card scanning selects random patient

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#84]
If you scan an insurance card, a random patient is being select. Something got mixed up here.

1. Longtap a package.
2. Add package to prescription.
3. Manually select a patient.
4. Longtap patient.
5. Scan insurance card.
6. See if wright patient was selected or not. If correct patient via Scan was found scan another card.
7. Now a patient will be found, but it is the wrong patient.

**Comment by bettar** [comment]
I cannot reproduce it, because the second card that I have for scanning will always fail.
