### ISSUE TITLE
amk File should be able to be shared with any file

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#85]
At the moment the amk File can only be shared with Mail. The user should be able to share the amk file with any App that is able to accept the AMK file. That is the way it used to work.

**Comment by bettar** [comment]
When sharing with the app Messages the email body also gets shared. Is that okay ?

**Comment by zdavatz** [comment]
see:  c761b6c2b19a93ad7caf60aaadd

**Comment by zdavatz** [comment]
Yes, that is totally fine.
