### ISSUE TITLE
Wrong patient found after scanning

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#86]
1. Create Doctor
2. Scan Patient A. Create Patient A including Tel and Email.
3. Scan Patient B. Create Patient B including Tel and Email.
4. Show prescription with Patient B. Do not save.
5. Add one package (Ponstan Suspension). Do not save.
6. Longtap on patient. 
7. Scan Patient B.
8. Patient A is still there.

**Comment by zdavatz** [comment]
When you click on the history of the patient and select a prescription then the right patient is shown.

**Comment by bettar** [comment]
It's not that the "wrong" patient is found, the functionality was implemented like that, preventing a change of patient if the prescription was in an edited state. Maybe the thinking was that if the doctor has started editing the medicines for a patient, it wouldn't make sense to change the patient and losing the changes for the previous patient. Up until now if the doctor wanted to reuse a prescription from a patient and use it for another patient, the change of patient needed to be the first step in editing a prescription.  From now on, that is to resolve issue #86, it will be possible to replace the patient even for an "unsaved" prescription. Note that if the previous functionality is preferred it would make sense to disable the health card scanning if the prescription has been edited. This could be easily achieved.

**Comment by zdavatz** [comment]
So why does selecting a patient from the address book then work? It is only the scanning that does not work and not select the patient.

**Comment by zdavatz** [comment]
fixed with 533e80c205ef276ed7e1252a9a614b9c6e8c5d1
