### ISSUE TITLE
Do "diacritic insensitive" searches for titles in the DB

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#89]
See: https://github.com/zdavatz/aips2sqlite/issues/3

**Comment by zdavatz** [comment]
this issue could also have been solved using `NSPredicate API`

**Comment by b123400** [comment]
I think NSPredicate API is not suitable for searching data in database. If we use it, we will have to load the entire database and match them one by one in memory, which is slow, use more memory and cannot take advantage of Sqlite's ability. My solution of using GLOB and SQL means we can have the similar code across iOS/Android/Csharp etc, which IMO is better.
