### ISSUE TITLE
add Full-Text-Search for iPhone/iPad

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-iOS#91]
1. Start App.
2. Add abbreviation in the search options bar, all the way on the right
2.1 iPhone/iPad Portrait Mode: `VTS` de, `RPT` fr, `FTS` en 
2.2 iPad Landscape and Searchbar Placeholder: 
`Volltext Suche`
`Recherche plein-texte`
`Fulltext Search` 
2.3 iPhone Landscape: `Volltext`, `Plein-texte`, `Fulltext`
3. If the users selects `VTS` then the Full-Text-Search is initiated.
4. User enters i.e. "SAPP".
5. The first result is shown in the main window.
6. User selects a result in the Main Window, i.e. `SAPP`
7. The second result is shown in the Main Window, with a _Hamburger_ on either side. Clicking the _Hamburger_ on the right will show 9. Clicking the _Hamburger_ on the left will take you back to 5. Either 5 or 9 can of course also be swiped. Like this we can use the Fachinfo View with the _Hamburgers_ on either side.
8. User select a FI and is take the to first highlighted section with the word.
9. The user can also swipe in the Result-Overview from the right. If the user selects something from the Result Overview then main Window is resorted.
10. Show the search result counter as when you do the In-Text-Search and the ability to navigate the search result. Backward and Forward.
11. Add swipe gesture for search result screen.
12. Fulltext Search Favorites should work as well (show up in the Favorites list). The usual sorting for the first 5 sorting possibilities needs to work as well.
<img width="1339" alt="Screenshot 2019-07-13 at 18 31 44" src="https://user-images.githubusercontent.com/4953/61174206-756c6f80-a59d-11e9-85c4-3399942c388b.png">

**Comment by bettar** [comment]
It's not clear what text should appear for all combinations of: 3 languages (Eng Deu, Fra), 2 devices (iPhone, iPad), different orientations (portrait, landscape), 2 items (search bar and toolbar button), short and long text.

**Comment by bettar** [comment]
At point 2 above it's still not clear what text goes In the search control placeholder, and what text goes in the toolbar button.

**Comment by zdavatz** [comment]
Updating on iPhone Xr creates a crash:

```
/Users/zdavatz/Library/Developer/CoreSimulator/Devices/7FE7410A-350D-45BA-A692-53D6BAEAB1FF/data/Containers/Data/Application/20343D99-E17D-4934-A3D7-3286DE8B7F9B/Documents/drug_interactions_csv_de.csv
2019-07-24 18:21:30.472089+0200 AmiKoDesitin[1712:135770] -[MLViewController searchDatabaseWith:] 1451
2019-07-24 18:21:30.628902+0200 AmiKoDesitin[1712:135770] 4345 hits in 157ms
2019-07-24 18:21:30.630930+0200 AmiKoDesitin[1712:135770] -[MLViewController tableView:numberOfRowsInSection:] 2455, mUsedDatabase: 5, mCurrentSearchState: 0
2019-07-24 18:21:30.654097+0200 AmiKoDesitin[1712:135770] uncaught exception: *** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array
2019-07-24 18:21:30.654332+0200 AmiKoDesitin[1712:135770] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e04a8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010d1b7ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010df98fac _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010df77077 -[__NSArrayM objectAtIndexedSubscript:] + 151
	4   AmiKoDesitin                        0x0000000109eb9e61 -[MLViewController tableView:heightForRowAtIndexPath:] + 161
	5   UIKitCore                           0x000000011139d2a2 -[UITableView _dataSourceHeightForRowAtIndexPath:] + 107
	6   UIKitCore                           0x00000001113ae383 __66-[UISectionRowData refreshWithSection:tableView:tableViewRowData:]_block_invoke + 371
	7   UIKitCore                           0x00000001113adbd5 -[UISectionRowData refreshWithSection:tableView:tableViewRowData:] + 3257
	8   UIKitCore                           0x00000001113b1d8c -[UITableViewRowData numberOfRows] + 95
	9   UIKitCore                           0x0000000111369dd6 -[UITableView noteNumberOfRowsChanged] + 117
	10  UIKitCore                           0x0000000111369394 -[UITableView reloadData] + 1489
	11  AmiKoDesitin                        0x0000000109ea809c -[MLViewController resetDataInTableView] + 188
	12  AmiKoDesitin                        0x0000000109ea7011 -[MLViewController finishedDownloading:] + 433
	13  CoreFoundation                      0x000000010df8c7bc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	14  CoreFoundation                      0x000000010df8bc3f _CFXRegistrationPost + 447
	15  CoreFoundation                      0x000000010df8b983 ___CFXNotificationPost_block_invoke + 227
	16  CoreFoundation                      0x000000010e06f7c2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1858
	17  CoreFoundation                      0x000000010df8b2d1 _CFXNotificationPost + 977
	18  Foundation                          0x000000010ace7ddb -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	19  AmiKoDesitin                        0x0000000109ec2926 -[MLCustomURLConnection unzipDatabase] + 1990
	20  AmiKoDesitin                        0x0000000109ec2124 -[MLCustomURLConnection connectionDidFinishLoading:] + 324
	21  CFNetwork                           0x000000010f6af7bb __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 53
	22  Foundation                          0x000000010acf033e __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	23  Foundation                          0x000000010acf0246 -[NSBlockOperation main] + 68
	24  Foundation                          0x000000010aced120 -[__NSOperationInternal _start:] + 688
	25  Foundation                          0x000000010acf2e87 __NSOQSchedule_f + 227
	26  libdispatch.dylib                   0x000000010eb9cd7f _dispatch_call_block_and_release + 12
	27  libdispatch.dylib                   0x000000010eb9ddb5 _dispatch_client_callout + 8
	28  libdispatch.dylib                   0x000000010ebab080 _dispatch_main_queue_callback_4CF + 1540
	29  CoreFoundation                      0x000000010dfb1a79 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	30  CoreFoundation                      0x000000010dfac126 __CFRunLoopRun + 2310
	31  CoreFoundation                      0x000000010dfab4d2 CFRunLoopRunSpecific + 626
	32  GraphicsServices                    0x00000001158e92fe GSEventRunModal + 65
	33  UIKitCore                           0x0000000111152fc2 UIApplicationMain + 140
	34  AmiKoDesitin                        0x0000000109e51610 main + 112
	35  libdyld.dylib                       0x000000010ec12541 start + 1
	36  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by zdavatz** [comment]
Make the side-page a bit wider, so the numbers fit as well.
<img width="373" alt="Bildschirmfoto 2019-07-26 um 13 32 13" src="https://user-images.githubusercontent.com/4953/61949080-f407da80-afa9-11e9-860d-e66316bb554e.png">

**Comment by zdavatz** [comment]
Increase the font of the search result, so it is the same size like the FI search result.

<img width="365" alt="Bildschirmfoto 2019-07-26 um 13 41 34" src="https://user-images.githubusercontent.com/4953/61949462-4695c680-afab-11e9-9712-ab509be4427f.png">
<img width="355" alt="Bildschirmfoto 2019-07-26 um 13 41 51" src="https://user-images.githubusercontent.com/4953/61949463-4695c680-afab-11e9-93dd-79342f0b247b.png">

**Comment by zdavatz** [comment]
Footer still has black background, it should go all the way down.
<img width="381" alt="Bildschirmfoto 2019-07-26 um 13 41 58" src="https://user-images.githubusercontent.com/4953/61949549-82c92700-afab-11e9-8c90-88c5dcb36201.png">

**Comment by zdavatz** [comment]
grey of the header is different from the grey of the FI search result.
<img width="398" alt="Bildschirmfoto 2019-07-26 um 13 42 03" src="https://user-images.githubusercontent.com/4953/61949586-9f655f00-afab-11e9-9606-5e53cd3ea55e.png">

**Comment by zdavatz** [comment]
<img width="350" alt="Bildschirmfoto 2019-08-02 um 17 52 01" src="https://user-images.githubusercontent.com/4953/62383411-fccf5200-b54f-11e9-84af-62d24111d983.png">

1. Search for _SAPP_
2. Click on

**Comment by bettar** [comment]
> grey of the header is different from the grey of the FI search result.
> <img alt="Bildschirmfoto 2019-07-26 um 13 42 03" width="398" src="https://user-images.githubusercontent.com/4953/61949586-9f655f00-afab-11e9-9606-5e53cd3ea55e.png">
> 
> ![B361919A-5B02-4ECE-8E53-1552B1D41807](https://user-images.githubusercontent.com/4953/62384336-cba84f00-b55a-11e9-9cbd-4d08cd3c311b.jpeg)

![Screenshot 2019-08-06 at 14 17 32](https://user-images.githubusercontent.com/9733270/62539518-a6b32500-b855-11e9-9302-0d008b8b9ccf.png)
![Screenshot 2019-08-06 at 14 18 55](https://user-images.githubusercontent.com/9733270/62539542-aca90600-b855-11e9-8c76-ebd9343c2a19.png)

**Comment by zdavatz** [comment]
It is a bit too wide now.

**Comment by zdavatz** [comment]
Fulltext-Search Crash

```
2019-08-10 21:55:50.872660+0200 CoMedDesitin[9537:849496] uncaught exception: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
2019-08-10 21:55:50.872898+0200 CoMedDesitin[9537:849496] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001121378db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011129cac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112085fac _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00000001120624c7 -[__NSArrayM objectAtIndex:] + 151
	4   CoMedDesitin                        0x000000010e2c6486 -[MLDBAdapter searchId:] + 57
	5   CoMedDesitin                        0x000000010e2e7b33 -[MLViewController tableView:didSelectRowAtIndexPath:] + 314
	6   UIKitCore                           0x0000000115461d4d -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1810
	7   UIKitCore                           0x0000000115461f61 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 337
	8   UIKitCore                           0x000000011524f0e9 _runAfterCACommitDeferredBlocks + 318
	9   UIKitCore                           0x000000011523e5b9 _cleanUpAfterCAFlushAndRunDeferredBlocks + 358
	10  UIKitCore                           0x000000011526b923 _afterCACommitHandler + 124
	11  CoreFoundation                      0x000000011209e2c7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	12  CoreFoundation                      0x000000011209878e __CFRunLoopDoObservers + 430
	13  CoreFoundation                      0x0000000112098e01 __CFRunLoopRun + 1505
	14  CoreFoundation                      0x00000001120984d2 CFRunLoopRunSpecific + 626
	15  GraphicsServices                    0x0000000119aa92fe GSEventRunModal + 65
	16  UIKitCore                           0x0000000115243fc2 UIApplicationMain + 140
	17  CoMedDesitin                        0x000000010e2b5722 main + 80
	18  libdyld.dylib                       0x0000000112d03541 start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by zdavatz** [comment]
Font is to big:
<img width="597" alt="Bildschirmfoto 2019-08-10 um 22 08 27" src="https://user-images.githubusercontent.com/4953/62826421-7227cc00-bbbb-11e9-9d91-f4b19061fd44.png">

**Comment by zdavatz** [comment]
3 Tap crashes App.
<img width="597" alt="Bildschirmfoto 2019-08-10 um 22 15 06" src="https://user-images.githubusercontent.com/4953/62826478-9b952780-bbbc-11e9-88d9-6d0ba75ceabe.png">

**Comment by zdavatz** [comment]
sometimes font is big sometimes font is small.

<img width="344" alt="Bildschirmfoto 2019-08-10 um 22 21 47" src="https://user-images.githubusercontent.com/4953/62826519-59201a80-bbbd-11e9-9c0e-db643a1d766b.png">
<img width="346" alt="Bildschirmfoto 2019-08-10 um 22 21 57" src="https://user-images.githubusercontent.com/4953/62826520-59b8b100-bbbd-11e9-8058-87b0eda6e2f6.png">
<img width="346" alt="Bildschirmfoto 2019-08-10 um 22 22 05" src="https://user-images.githubusercontent.com/4953/62826521-59b8b100-bbbd-11e9-87d0-c30fc5eab4ee.png">

**Comment by zdavatz** [comment]
font is to big.
<img width="740" alt="Bildschirmfoto 2019-08-10 um 22 28 00" src="https://user-images.githubusercontent.com/4953/62826569-24609300-bbbe-11e9-873f-20d2fadcaf57.png">

**Comment by zdavatz** [comment]
add swipe gesture for this screen.

![7B0F86DE-C374-40BA-8317-A6BC6AAC524A](https://user-images.githubusercontent.com/4953/62926793-e29e3b00-bdbd-11e9-9300-c0a638b72835.png)

**Comment by zdavatz** [comment]
Adjust right pane size.

<img width="817" alt="Bildschirmfoto 2019-08-17 um 07 06 21" src="https://user-images.githubusercontent.com/4953/63206909-c94b0680-c0bd-11e9-915b-2ea97f063806.png">

**Comment by zdavatz** [comment]
Font increases after rotation: https://ywesee.slack.com/files/U27FC8WLA/FM42936NP/rpreplay_final1566018848.mp4

**Comment by zdavatz** [comment]
Also see: https://github.com/zdavatz/cpp2sqlite/issues/98

**Comment by bettar** [comment]
> Adjust right pane size for iPad.
> 
> <img alt="Bildschirmfoto 2019-08-17 um 07 06 21" width="817" src="https://user-images.githubusercontent.com/4953/63206909-c94b0680-c0bd-11e9-915b-2ea97f063806.png">

The picture seems to show the Fachinfo results. Is the problem with Fachinfo or Full Text ?

**Comment by zdavatz** [comment]
Fulltext.
