### ISSUE TITLE
Fachinfo search results navigate in the wrong direction

### ISSUE THREAD

**Issue by bettar** [zdavatz/AmiKo-iOS#95]
The current navigation of search results in the Fachinfo is offset by one.

1. Search Praparat for "Exviera"
2. In the result list tap "Exviera" to display the Fachinfo
3. Search for "SAPPHIRE". There are 12 results and the first one is correctly positioned at the top of the screen
4. Problem: after navigating to the next highlight and back to the previous highlight, a different highlight is at the top of the screen. 
5. More info: to display the original first highlight result we need to click "Prev" once more, but then the index shows "12/12" instead of "1/12"

**Comment by zdavatz** [comment]
Ok, let's fix it.

**Comment by bettar** [comment]
Some more insight: maybe the items are not offset by one, but the whole array index is reversed, so that instead of navigating forward we navigate backwards
